#spring.application.name=wine-note

#db\uD3EC\uD2B8 \uBCC0\uACBD
server.port=8081

#H2 ?????? ??? ???? ????
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#db?? ?? (???? ??)
spring.datasource.url=jdbc:h2:mem:winenote
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=1234

#JPA? ???? SQL? ??? ??
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
