# \uC2A4\uD504\uB9C1 \uC560\uD50C\uB9AC\uCF00\uC774\uC158 \uC774\uB984
spring.application.name=wine-note

# DB \uD3EC\uD2B8 \uBCC0\uACBD (8080 \uCDA9\uB3CC \uBC29\uC9C0)
server.port=8081

# H2 \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uCF58\uC194 \uC6F9 \uD654\uBA74 \uD65C\uC131\uD654
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# DB \uC5F0\uACB0 \uC124\uC815 (\uBA54\uBAA8\uB9AC \uBAA8\uB4DC)
spring.datasource.url=jdbc:h2:mem:winenote
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=1234

# JPA \uC2E4\uD589 SQL \uB85C\uADF8 \uCD9C\uB825
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update